####################################################################
# PERFIL: PRODUCCION (Render)
# Activar con variable de entorno: SPRING_PROFILES_ACTIVE=prod
# Todas las credenciales SIEMPRE vienen de variables de entorno de Render.
####################################################################

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=validate

server.error.include-stacktrace=never
server.error.include-message=never

logging.level.root=WARN
logging.level.com.bodegazo.ferreteria=INFO
