####################################################################
# PERFIL: DESARROLLO (Eclipse / entorno local)
# Activar con: -Dspring.profiles.active=dev
####################################################################

spring.datasource.url=jdbc:postgresql://localhost:5433/bodegazo_teja?currentSchema=bodegazo
spring.datasource.username=postgres
spring.datasource.password=bodegazodelateja

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate

logging.level.com.bodegazo.ferreteria=DEBUG
logging.level.org.hibernate.SQL=DEBUG
